### ISSUE TITLE
ServiceBus template only supports queues

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-webjobs-sdk-templates#101]
The current templates only supports using service bus queues. There is no option to use a topic and the user must go into the advanced editor and have knowledge of the property name.

We're likely dealing with a UI limitation here as well, but we could address this by having one template for Service Bus Queues and another for Service Bus Topics in the meantime.

**Comment by soninaren** [comment]
This is dup of https://github.com/Azure/azure-webjobs-sdk-templates/issues/134

Closing this one.
