### ISSUE TITLE
Easy Tables binding is confusing to Mobile Apps developers

### ISSUE THREAD

**Issue by ggailey777** [Azure/azure-webjobs-sdk-templates#108]
In Functions, the "Easy Tables" binding uses the URL of a mobile app, which it looks like can be any table exposed by a App Service mobile app. In Mobile Apps, an "Easy Table" is usually a Node.js backend service, since Easy Tables in the portal doesn't support .NET backend. 

This makes "Easy Tables" confusingly overloaded. Instead of Easy Tables we should call it Mobile Tables.

**Comment by paulbatum** [comment]
Closing this one, see related issue in script repo. https://github.com/Azure/azure-webjobs-sdk-templates/issues/108

**Comment by paulbatum** [comment]
Reactivating. Before I port this bug to the right repo (after failing the first time), we should just decide whether we are likely to take this change.

**Comment by mathewc** [comment]
I was just reading this and it confused the hell out of me :)

**Comment by ggailey777** [comment]
@mathewc is it my description that is confusing? I can try to be more clear.

**Comment by ggailey777** [comment]
Here's an email thread where this is discussed with Adrian and Paul:
[RE Easy Tables.pdf](https://github.com/Azure/azure-webjobs-sdk-templates/files/207732/RE.Easy.Tables.pdf)

**Comment by christopheranderson** [comment]
I've created a new issue with a "Fix to this" here: https://github.com/Azure/azure-webjobs-sdk-templates/issues/139

We'll close this one if we decide to do the rename.
