### ISSUE TITLE
Add the ability to Disable a template

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-templates#119]
So we can just flip a switch and have a template yanked if it has a problem, rather than having to delete the template (which we've had to do a few times now).

**Comment by soninaren** [comment]
We need a corresponding issue in portal to consume the switch

**Comment by alrod** [comment]
@soninaren, give me the name of property in metadata.json. bool hidden ?

**Comment by soninaren** [comment]
We can keep it as the name of the property, Which ever is easier for you.
#### "visible": "true"

**Comment by soninaren** [comment]
Also lets keep the template visible if the property is missing otherwise we will have to touch all the templates

**Comment by alrod** [comment]
ok, "visible": false to hide template. if missed template will be shown.

**Comment by soninaren** [comment]
yes

**Comment by christopheranderson** [comment]
This is implemented. No further work is needed.
