### ISSUE TITLE
Add Try-Functions metadata

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-webjobs-sdk-templates#129]
We need metadata for both bindings and templates that indicates whether they are applicable in try functions mode (because in this mode you have access to a limited number of resource types e.g. you have storage but not NH/ServiceBus/DocDB/etc)

**Comment by alrod** [comment]
@soninaren, are you going to start working on this?

**Comment by soninaren** [comment]
I have not received any word about backend work done on this one. At the moment it is in backlog.

**Comment by soninaren** [comment]
#271
