### ISSUE TITLE
Queue Trigger Powershell Function

### ISSUE THREAD

**Issue by nirmash** [Azure/azure-webjobs-sdk-templates#13]
Consider removing this one if we don't have a good powershell story. If not, this one seems to have table output so we either change to blob to be consistent with the other ones or at least rename the template to Queue Trigger to Table Storage Powershell Function

**Comment by christopheranderson** [comment]
I think the right policy here is to have an "experimental" category. Classify the PowerShell/Python/PHP scenarios as "experimental" until we can make them 1st class.

**Comment by mathewc** [comment]
All these various templates were imported verbatim from my initial sample set and weren't really intended as starter templates for wide use :) I just created a bunch of templates to show off various bindings and all their bells and whistles.

For the templates, I think we should keep them as simple as possible.

**Comment by christopheranderson** [comment]
This has been implemented.
