### ISSUE TITLE
Easy tables binding with authentication

### ISSUE THREAD

**Issue by ggailey777** [Azure/azure-webjobs-sdk-templates#135]
Consider that I have an existing easy table that I am using with my mobile apps, which I have protected with authentication because an API key IS NOT a security token since it's getting distributed with my mobile apps onto devices and it can be obtained. 

How can I get my Azure Function to access my easy table by using authentication, or will this never be a supported scenario?

**Comment by fabiocav** [comment]
Currently, it can't. The API key **exposed by Functions** is to support integration scenarios with trusted systems and it is to be kept private/secure. The API key support **added to easy tables** is to validate requests from Azure Functions. We should **not** recommend using either of those keys on any mobile or any other distributed client applications.
Keep in mind that mobile clients can continue to use the Mobile Apps APIs following the standard authentication process. Enabling API key use on a particular table doesn't mean that the clients need to use that key for auth.
Easy Auth support and improving how the tokens flow to work into easy tables is definitely the goal, but those are backlog items at this point.

**Comment by soninaren** [comment]
Closing the issue from on this repo. discussing offline with fabio. This would require an update to https://github.com/Azure/azure-webjobs-sdk-extensions to be consumed by https://github.com/Azure/azure-webjobs-sdk-script/. Filing an issue in the script sdk repository. https://github.com/Azure/azure-webjobs-sdk-script/issues/233
