### ISSUE TITLE
Rename the Easy Tables binding to Mobile Tables binding in UX

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-webjobs-sdk-templates#139]
We need to change "Easy Tables" to "Mobile Tables".

**Comment by mathewc** [comment]
But we're going to do that across the board, right? The actual WebJobs Extension, then consume that in Script repo, etc. @brettsam

**Comment by brettsam** [comment]
Yes, we should. I believe @christopheranderson is suggesting that we go the other way and rename the ux-facing bits (templates, function.json, docs) first if we can, and then I can do it everywhere else. 

The 'type' for easyTable bindings will have to change to mobileTable -- which will break anyone that's using this. How do we communicate that?

**Comment by mathewc** [comment]
I think it'd be better to go the other way - change the name in all the implementation first before releasing the public UI updates. That way, if we find any other oddities with the rename, we can work all that out before we change the UI.

**Comment by christopheranderson** [comment]
I think changing the UI and docs first is the best user experience.

The issue we're facing right now is that writing the documentation for the existing name is kind of hard because the name is wrong, so we have to explain, in the docs, what easy tables means in Functions vs what it means in the actual Mobile product. A UI update is a few lines in the bindings.json and the user impact of the underlying implementation having a different name is extremely low. Refactoring all the code is going to take much longer - thus resulting in either no docs or poor docs, which isn't good for the users.

Are there any large risks for the user experience if we do the UI rename before the refactor?

**Comment by soninaren** [comment]
#173 fixes this
