### ISSUE TITLE
HttpTrigger C# returning 500's when called externally from a browser

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-webjobs-sdk-templates#14]
After creating an HttpTrigger when we called from within the portal returns 400 (Expected as per template). However when hitting the trigger from a browser returns 500.

**Comment by davidebbo** [comment]
Which specific template did you use? Was is JS or C#? Anything interesting in your `D:\home\LogFiles\Application\Functions\Host`?

**Comment by davidebbo** [comment]
I just tried both and could not repro. Please check your log.

**Comment by davidebbo** [comment]
Seems issue is that the Functions v2 UI is generating the wrong files. Try v1 instead.

**Comment by davidebbo** [comment]
This is tracked by https://github.com/projectkudu/WebJobsPortal/issues/24
