### ISSUE TITLE
ServiceBus Topic Template

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-templates#157]
I recently responded to a SO post where a user was trying to trigger a function on a ServiceBus topic (https://stackoverflow.com/questions/36707496/how-to-use-a-servicebus-trigger-with-a-topic-subscription-in-an-azure-function). The runtime supports this, but he had to go to the advanced editor to enable make it work.

Recommend creating a separate template for this. Also there might be portal work that needs to be done to expose UI for setting the topic/subscription.

**Comment by soninaren** [comment]
Portal work for Service Bus Binding UI is done. It is available in the next portal at the moment. I will create a service bus topic template for the templates repo.
