### ISSUE TITLE
Create "Parameter Name" setting for every binding and remove "defaultParameterName", "parameterNamePrompt"

### ISSUE THREAD

**Issue by alrod** [Azure/azure-webjobs-sdk-templates#159]

**Comment by alrod** [comment]
@christopheranderson, @soninaren for visibility

**Comment by soninaren** [comment]
I agree we should have the parameter name as a setting. This will make all the settings consistent and we will be able to apply all settings related logic to the parameter name.

**Comment by christopheranderson** [comment]
This needs to ship before the portal changes ship. @soninaren, please work closely with @alrod.

**Comment by soninaren** [comment]
#169 fixes this.
