### ISSUE TITLE
Support AcesssRights setting for Service Bus

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-webjobs-sdk-templates#160]
From https://github.com/projectkudu/AzureFunctionsPortal/issues/348

> See SO post http://stackoverflow.com/questions/36705464/servicebus-queue-trigger-for-azure-function-manage-claim-is-required-for-this-o

> The ServiceBusTrigger/ServiceBus bindings support an AccessRights property. We need to add UI for this.

This requires a bindings.json update.

**Comment by christopheranderson** [comment]
@mathewc - Why is AccessRights useful here? Isn't it implicit from the Input/Output? For Input, can't we just set this to "Listen"? For Output, we set this to "Send" or "Manage"? Maybe we only need it for Output?

**Comment by mathewc** [comment]
See core SDK issue here for background: https://github.com/Azure/azure-webjobs-sdk/issues/501

Basically we always assumed we had Manage rights, and the SDK has CreateIfNotExists semantics - if an SB entity didn't exist we'd try to create it. If a connection doesn't have Manage, the level can be explicitly specified, in which case the SDK won't attempt operations it doesn't have rights to perform.

**Comment by soninaren** [comment]
So the suggested UI for trigger AccessRights would have Listen and manage options in the drop down, Where as for output binding we would have Send and Manage rights as options.
