### ISSUE TITLE
blobTrigger doesn't work with node.js

### ISSUE THREAD

**Issue by janpavtel** [Azure/azure-webjobs-sdk-templates#185]
## Node.js session:

code:
```
module.exports = function (context, myBlob) {
    context.log('Node.js blob  id:', myBlob.id);
    context.log('Node.js blob:', myBlob);
    context.done();
};
```

config:
```
{
  "bindings": [
    {
      "name": "myBlob",
      "type": "blobTrigger",
      "direction": "in",
      "path": "sample",
      "connection": "******_STORAGE"
    }
  ],
  "disabled": false
}
```

upload blob using azure cli: 
```
azure storage blob upload  one.txt sample  example/first.txt
```
console output:
```
2016-05-06T07:05:42  Welcome, you are now connected to log-streaming service.
2016-05-06T07:06:12.091 Function started (Id=84da8dda-2e6d-4b8f-be6f-2d52045a23f0)
2016-05-06T07:06:12.106 Node.js blob  id: undefined
2016-05-06T07:06:12.106 Node.js blob:
2016-05-06T07:06:12.106 Function completed (Success, Id=84da8dda-2e6d-4b8f-be6f-2d52045a23f0)
```

As you can see there is no information about blob object.

## Csharp session:

code:
```
#r "Microsoft.WindowsAzure.Storage"

using Microsoft.WindowsAzure.Storage.Blob;

public static void Run(ICloudBlob myBlob, TraceWriter log)
{
    log.Verbose($"Processing file: {myBlob.Name}");
    
}
```
config:
```
{
  "bindings": [
    {
      "name": "myBlob",
      "type": "blobTrigger",
      "direction": "in",
      "path": "sample",
      "connection": "******_STORAGE"
    }
  ],
  "disabled": false
}
```
upload blob using azure cli: 
```
azure storage blob upload  one.txt sample  example/first.txt
```
console output:
```
2016-05-06T07:08:41  Welcome, you are now connected to log-streaming service.
2016-05-06T07:09:08.905 Function started (Id=5aa08209-aa8e-455c-a28e-c34b1709179d)
2016-05-06T07:09:08.905 Processing file: example/first.txt
2016-05-06T07:09:08.905 Function completed (Success, Id=5aa08209-aa8e-455c-a28e-c34b1709179d)
```
Using Csharp we received blob information.
Maybe there is error in  [BlobTrigger - Node template example](https://github.com/Azure/azure-webjobs-sdk-templates/tree/master/Templates/BlobTrigger-NodeJS)

**Comment by soninaren** [comment]
BlobTrigger-Node template expects data in json format with an id. That is why you would be getting undefined.
```JSON
{
    "id":"foobar123"
}
```
You can test the BlobTrigger-Node template by clicking the Run button in the portal. Make sure you have the data in the above format in the Run textbox.

C# actually is using named parameter to get the name of the uploaded blob that is why you are seeing. blob path.

**Comment by janpavtel** [comment]
How I should change node.js code in order to get blob name that I store into blob storage using azure cli? I'm using azure function service

**Comment by soninaren** [comment]
You can access that information via ``context.bindingData.BlobTrigger``.

So the new line of code would be 
```JAVASCRIPT
 context.log('Blob path:', context.bindingData.BlobTrigger);
```

**Comment by janpavtel** [comment]
Excellent. It's working. Thank you for quick help. Maybe it's worth to add one more example (with ' context.bindingData.BlobTrigger' ) into templates directory.

**Comment by Omgan** [comment]
I have a BlobTrigger event (Which fires when blob is added in to the container) : 

**index.js :**
`module.exports = function (context/*, myBlob*/) {
    context.log("Full blob path:", context.bindingData.blobTrigger);
    context.done();
};
`
**function.json**
`{
  "bindings": [
    {
      "name": "myBlob",
      "type": "blobTrigger",
      "direction": "in",
      "path": "my-container/{name}",
      "connection": "MY_STORAGE_ACCOUNT"
    }
  ],
  "disabled": false
}`

if the file is larger than 250MB, the  function app crashes
if it is lesser it prints the "Full blob path: my-container/my-file.myext"

what should i do.

but in C# it works fine for both >250MB and <250MB

How to solve this?
