### ISSUE TITLE
Rename all templates code files to run.*

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk-templates#198]
With anything else, it blows up if user adds a second file, unless they add a source attribute, which we have no UI for.

**Comment by mathewc** [comment]
I don't think we want to rename Node entry points to run.js - index.js is more natural for Node I think. Are you talking about C# only?

Do you think we should add UI for the source metadata property? I think we should actually rename that property btw.

**Comment by davidebbo** [comment]
The key is to make sure the following scenario is not broken:

- new function from template. It works
- add some random other file in the function folder. Now your function is broken

And that's the situation we're in now (e.g. I tested with Python). Alternate solution would be to explicitely add the source attrib to all function.json from templates.

**Comment by soninaren** [comment]
Tested the above scenario with Node. Works fine. Will update other template for other languages. Leaving node as is.

**Comment by davidebbo** [comment]
I think for Node we may have special casing for index.js. If you call it foo.js it blows up too.

**Comment by soninaren** [comment]
So node at least requires either index.js or run.js in the functions folder. So the following scenarios are working
- Scenario 1 (working)
1) Deploy a function with index.js
2) add foo.js

- Scenario 2 (working)
1) Deploy a function with run.js
2) add foo.js
3) add index.js

- Scenario 3 (not working)
1) Deploy a function with foo.js (No run.js or index.js present)

Scenario 3 would be a portal bug.

**Comment by soninaren** [comment]
#198 fixes this.
