### ISSUE TITLE
Please simplify the C# HTTP Trigger Template

### ISSUE THREAD

**Issue by nirmash** [Azure/azure-webjobs-sdk-templates#206]
Few points of feedback coming from the POV of someone who demos the product a lot.
1) It is good that the template handles the post body as well as the query string, we should keep this 
2) the code itself is too complicated, getting the name from the query string with Linq is not intuitive, I suggest we use an input object that ends up like req["name"].
3) name = name ?? data?.name; is a bit confusing, I would suggest using a good old if statement so it is a bit more readable

**Comment by soninaren** [comment]
There was some work done and some discussion on this before.
https://github.com/Azure/azure-webjobs-sdk-templates/issues/63
https://github.com/Azure/azure-webjobs-sdk-templates/pull/83

@fabiocav do you want take a look ath this?

**Comment by fabiocav** [comment]
@soninaren the issue and PR you're referring to are old and closed/completed. With the latest HTTP binding enhancements, we can further simplify the default HTTP template.

**Comment by soninaren** [comment]
@nirmash: comments to the corresponding points.
1) I definitely agree with this point that we should keep the implementation with both query string and body.
2) The changes to http trigger/binding only provides simpler implementation to get request body, however it does not provide a simpler way of fetching query string.
3) Changing `name = name ?? data?.name` will give us the following line. I am not sure if that solves the purpose of adding more readability to code. I am happy to change it.
```csharp
if (name == null && data != null && data.name != null)
{
    name = data.name
}
```
