### ISSUE TITLE
Need to validate CRON expressions for TimerTrigger

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-templates#211]
And prevent invalid expressions, including TimeSpan expressions. See Runtime issue https://github.com/Azure/azure-webjobs-sdk-script/issues/400.

We've already fixed the doc as well - it was telling people that TimeSpan was supported.

**Comment by davidebbo** [comment]
This changed caused a regression as it's blocking many valid cron expressions. See https://github.com/projectkudu/AzureFunctionsPortal/issues/408. Can @soninaren can you please revert of fix asap? Thanks

**Comment by soninaren** [comment]
reverting this via #234
