### ISSUE TITLE
need info on authorization

### ISSUE THREAD

**Issue by vance** [Azure/azure-webjobs-sdk-templates#212]
The web-client for functions clearly shows the access token in the URL. How do I configure this with a CI/Github deployed function? is it host.json? Please document this somewhere. I downloaded the publish settings file but unsure what I need to add to my repository.

**Comment by mathewc** [comment]
We have detailed documentation on this here: https://azure.microsoft.com/en-us/documentation/articles/functions-create-a-web-hook-or-api-function/

**Comment by mathewc** [comment]
The location and format of the secrets files used for WebHook/Http functions is documented in the "Api keys" section here: https://azure.microsoft.com/en-us/documentation/articles/functions-bindings-http-webhook/. Is this what you're looking for?

**Comment by vance** [comment]
thanks. nowhere there does it say you have to CMD into in d:/home/data/Functions/Secret and do a more on the hosts json file... why make that so arcane (and slow with the web CMD), why not display it in a convenient location on a wedge? And, so is the function key then always the ?code= parameter for the function?

**Comment by mathewc** [comment]
What is a "wedge"?

Anyhow, you're really not supposed to have to mess with these files. Our Portal UI is supposed to manage setting them up properly, etc. as functions are created. That's why the doc is rough for this. Also, these file formats will likely undergo changes before we GA the service.

To set up a function "Foo", you create a Foo.json file containing the "key" secret. That will then be the required `?code=` parameter value.

**Comment by vance** [comment]
*blade=wedge. The docs are great for the blade managed functions, but does not cover the CI versions adequately.  I do not know how to connect to my Github hosted function.  Where do i get the `code` param for my function URL? It's right there in the web version, no idea where to get this for the Git version. https://MY_APP.azurewebsites.net/api/HttpTriggerNodeJS1?code=XXXX

**Comment by vance** [comment]
i"If the secrets folder contains a JSON file with the same name as a function" - it doesn't.

**Comment by mathewc** [comment]
I don't understand your last comment. Regarding secrets file layout, you can take a look at this example: [here](https://github.com/Azure/azure-webjobs-sdk-script/tree/dev/sample) is a functions folder with some sample functions, and [here](https://github.com/Azure/azure-webjobs-sdk-script/tree/dev/src/WebJobs.Script.WebHost/App_Data/secrets) is the corresponding secrets folder.

Anyhow, yes as you might expect, we've focused most of our limited doc resources on the primary Portal scenarios, so we're lacking in CI doc. I'll share that feedback with our doc team.

**Comment by vance** [comment]
It's just not clear. Am I retrieving these values from the filesystem with CMD prompt, adding a host.json to my function directory in www/ or are these values all self-defined? Like, should I be spelunking around in CMD for these values? Do I then have to make a new file in the www/ folder to specify the key again? 

To quote:
If the secrets folder contains a JSON file with the same name as a function, the key property in that file can also be used to trigger the function, and this key will only work with the function it refers to. For example, the API key for a function named HttpTrigger is specified in HttpTrigger.json in the secrets folder. Here is an example:

```
{
  "key":"0t04nmo37hmoir2rwk16skyb9xsug32pdo75oce9r4kg9zfrn93wn4cx0sxo4af0kdcz69a4i"
}
```

I don't see this in the secrets folder via CMD...

**Comment by vance** [comment]
![image](https://cloud.githubusercontent.com/assets/145471/15617577/69fb4ab4-23fe-11e6-9659-f252c2f1de88.png)

**Comment by vance** [comment]
> You can configure a function to require the master key by setting the authLevel property to "admin".

How do you do this? Easy for web made function (it's a tab). How to does one specify authLevel for a CI function? Is this what's required to even generate the `FunctionName.json --> key` file code?

**Comment by vance** [comment]
My problem with the templates may be totally off-base: I don't see my function as a read-only function in the list on the left of the home Functions App screen.... something's wrong/not configured correctly with my template?

**Comment by christopheranderson** [comment]
This is a usability issue on secrets management, which is going to be tracked here: https://github.com/projectkudu/AzureFunctionsPortal/issues/360

Closing this issue since the linked issue will help address this.
