### ISSUE TITLE
Consider renaming default binding parameter names

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-templates#221]
This is related to https://github.com/Azure/azure-webjobs-sdk-script/pull/419.

Lots of the function.json files for the templates use the default name "input" for input bindings. Are those names even used? Isn't it overridden by the default name specified in bindings.json?

If not used, we should remove them, otherwise this issue exists as a suggestion by @davidebbo to use more template appropriate names. E.g. rather than "input" for a blob trigger, use "myBlob" or whatever the established default name is for the binding.

**Comment by christopheranderson** [comment]
I'll share around a proposal on a naming strategy and rename them myself afterwards.

**Comment by mathewc** [comment]
I'd like to determine whether the values like "input" in function.json are even used - perhaps they aren't (overridden by values in bindings.json)?

**Comment by christopheranderson** [comment]
One thought - because we have docs now, in portal, we need to consider if the docs and the default names match up. I'd like to move towards using a more consistent naming policy across our defaults/docs/samples/etc. I think what the portal uses for defaults will be what we snap to.

**Comment by lindydonna** [comment]
@soninaren Can you tell me how to change these default names?  Is the portal documentation also in this repo?

**Comment by soninaren** [comment]
Default names are strings in the resource files. All bindings are present in bindings.json. 
For example for 

### Saas Table

- **Saas Table Name string**: [here](https://github.com/Azure/azure-webjobs-sdk-templates/blob/dev/Bindings/bindings.json#L560)
- **Location in resource file**: [here] (https://github.com/Azure/azure-webjobs-sdk-templates/blob/a211ff1d3cedd32e042df181f1bd6b6574c12a7b/Resources/Resources.resx#L372)

### Documentation info
- **Markown file reference for documentation in binding.json** [here](https://github.com/Azure/azure-webjobs-sdk-templates/blob/dev/Bindings/bindings.json#L563)
- **Markdown file:** [here](https://github.com/Azure/azure-webjobs-sdk-templates/blob/dev/Documentation/apiHubTable.md)

**Comment by christopheranderson** [comment]
Booting this because it's too big for rc

**Comment by soninaren** [comment]
fixed in #363

**Comment by soninaren** [comment]
fixed in here https://github.com/Azure/azure-webjobs-sdk-templates/pull/365
