### ISSUE TITLE
ApiHub bindings settings need regex validators in binding.json

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-webjobs-sdk-templates#227]
The following settings are missing regex validators. We should try and add validators where applicable.

apiHubTable-input binding
•	dataSetName
•	tableName
•	endtityId

apiHubTable-output binding
•	dataSetName
•	tableName
•	endtityId

apiHubFile-input binding
•	path

apiHubFile-output binding
•	path

apiHubFileTrigger
•	path

**Comment by christopheranderson** [comment]
@soninaren - is this still active?

**Comment by soninaren** [comment]
yes, We need regex for the above mentioned bindings

**Comment by safihamid** [comment]
I sent an email about this. There is no Regex across all providers.

**Comment by soninaren** [comment]
Well in that case we can close this issue.

**Comment by mathewc** [comment]
Thanks for confirming Hamid.
