### ISSUE TITLE
Generic webhook template should not ask for any parameters

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-webjobs-sdk-templates#23]
We have a generic webhook template in the core category, but once you select it, you are asked to specify the type of webhook.

**Comment by davidebbo** [comment]
Yes, that feels broken. Also, if you want plain http, the only way to do it today is to choose WebHook and then say that you don't want it to be a WebHook, which is quirky :)

**Comment by soninaren** [comment]
This was a portal bug has been fixed in the latest deployment. Generic webhook does not ask to select the type of webhook anymore.

**Comment by soninaren** [comment]
The plain http trigger was also fixed by portal deployment
