### ISSUE TITLE
Fix the case for documentdb binding type

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-webjobs-sdk-templates#238]
We need to redo this [commit](https://github.com/Azure/azure-webjobs-sdk-templates/commit/48fd7048f9b50da041d0e28e2950070218029c27) once this https://github.com/projectkudu/AzureFunctionsPortal/issues/411 issue is fixed

**Comment by mathewc** [comment]
Naren, can you reaply this now that the portal fix is in? Does the release need to be staged?

**Comment by soninaren** [comment]
need to redeploy portal before merging to master, can be tested in the dev portal.

**Comment by soninaren** [comment]
#253 fixed
