### ISSUE TITLE
Provide empty templates for all languages (including experimental)

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-templates#256]
E.g. it is hard to get started writing an Http triggered PHP function. I thought to start from an empty Node template, but that creates a primary file with the wrong extension, so that doesn't really work. Your only recourse is to go into Kudu and create everything manually.

If instead we had an empty template for each language, it would set everything up correctly.

**Comment by soninaren** [comment]
fixed in #262
