### ISSUE TITLE
escaped double quotes in some templates description

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-webjobs-sdk-templates#276]
![capture](https://cloud.githubusercontent.com/assets/645740/17234308/8527848c-54ec-11e6-9d2c-957a37bc072f.PNG)

**Comment by soninaren** [comment]
Fixed in commit https://github.com/Azure/azure-webjobs-sdk-templates/commit/bebe7b68ece1a8567b910b63701f02d710f6b17d
