### ISSUE TITLE
PowerShell HTTP Trigger template - Out-File "typo" (nice to have)

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-webjobs-sdk-templates#277]
From https://feedback.azure.com/forums/355860-azure-functions/suggestions/14807592-powershell-http-trigger-template-out-file-typo

> The template for HTTP trigger in PowerShell has a Out-file command
> 
> Out-File -Encoding Ascii $Env:res -inputObject "Hello $name"
> 
> it should be using the full parameter names to make it more understandable
> 
> Out-File -FilePath $Env:res -Encoding Ascii -inputObject "Hello $name"

**Comment by soninaren** [comment]
Fixed in commit https://github.com/Azure/azure-webjobs-sdk-templates/commit/e1cfdfc807cf6dfb9856473c78fdd22884208561
