### ISSUE TITLE
SendGrid CSharp Template Error

### ISSUE THREAD

**Issue by qin-nz** [Azure/azure-webjobs-sdk-templates#279]
I Create `SendGridCSharp1` on function portal using [SendGrid-CSharp](https://github.com/Azure/azure-webjobs-sdk-templates/tree/dev/Templates/SendGrid-CSharp)

After I create it using template, an error occurred.

```
Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.SendGridCSharp1'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'message' to type SendGridMessage&. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).
```

By the way, I don't know how to  configure the app setting "AzureWebJobsSendGridApiKey" with SendGrid Api key.

**Comment by mathewc** [comment]
To configure that key, simply add an app setting to your Function App using the portal. The instructions [here](https://azure.microsoft.com/en-us/documentation/articles/functions-scenario-database-table-cleanup/#set-a-sql-database-connection-string-in-the-function-app) show how to configure an app setting (though that article is about adding a DB connection string). Create a new setting with the correct name and your Api key as a value.

**Comment by qin-nz** [comment]
@mathewc Thank you for answer my question.

I open this issues is for the following error.
But after I configure the key, everything goes right.

![image](https://cloud.githubusercontent.com/assets/6998071/17443130/8515b632-5b6b-11e6-935e-3cfba23d13da.png)
