### ISSUE TITLE
Node.js Github Template is missing trailing semi colon

### ISSUE THREAD

**Issue by SyntaxC4** [Azure/azure-webjobs-sdk-templates#28]
Just assuming we don't want errors to show up with default experiences. it just requires one additional semi-colon

![image](https://cloud.githubusercontent.com/assets/441607/13689110/414be49e-e6db-11e5-9a2c-c504874ea944.png)

**Comment by davidebbo** [comment]
It's more of a warning, but we should fix it. We probably have same in many templates, so let's handle globally.
