### ISSUE TITLE
Add property to support Chaining in output bindings.

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-webjobs-sdk-templates#280]
**Output bindings**
- Storage
- Queues
- Storage Blobs
- Service Bus Queues
- Service Bus Topics
- Event Hub

**Comment by mathewc** [comment]
What is "chaining"?

**Comment by soninaren** [comment]
It is setting up functions in a way so that, output of one function is input for another.

**Comment by soninaren** [comment]
Added in the following commits
https://github.com/Azure/azure-webjobs-sdk-templates/commit/584ed92643ad92c0a5de5febf68399475b0c2e95
https://github.com/Azure/azure-webjobs-sdk-templates/commit/dac48bbbb3e01924616c18037ca0ee7472cb7ba0
