### ISSUE TITLE
ImageResizer template has extra space in nuget package version, breaking things

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk-templates#283]
From https://social.msdn.microsoft.com/Forums/en-US/6dc88da6-22df-4db7-b3fa-3fc06b10dc66/azure-function-imageresizer-sample-cant-find-imageresizer-type?forum=AzureFunctions:

The template has an extra space in it. 

   "ImageResizer": "4.0.5 "

**Comment by lindydonna** [comment]
I'll do the fix, please assign to me.
