### ISSUE TITLE
Rename SaaSFileTrigger and SaaSTable to more meaningful names

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-templates#298]
Working with the UX folks and discussions among the team, we will use the names ExternalFileTrigger and ExternalTable. I realize that source is not always "external" but we have no other official term to work with.

**Comment by mathewc** [comment]
Hopefully we can work towards consistency between the actual underlying names of the bindings ([as surfaced in metadata](https://github.com/Azure/azure-webjobs-sdk-script/tree/dev/sample/ApiHubFileTrigger)) and the names of the templates, etc. All the other bindings are consistent.

@safihamid May have some thoughts.

**Comment by lindydonna** [comment]
Yup, I noticed that too. The one advantage of the name "apiHub" being in there is that internally we know what it means.

CCing @mattchenderson for his feedback

**Comment by soninaren** [comment]
fixed in https://github.com/Azure/azure-webjobs-sdk-templates/pull/349
