### ISSUE TITLE
Missing $ for variable

### ISSUE THREAD

**Issue by jeffpatton1971** [Azure/azure-webjobs-sdk-templates#300]
I've deployed the following template 3 times, just to make sure I'm not crazy.

https://github.com/Azure/azure-webjobs-sdk-templates/tree/dev/Templates/HttpTrigger-Powershell

Each time, the leading $ for requestbody is missing, which causes the function to fail the simple test.

**Comment by jeffpatton1971** [comment]
The run.ps1 in the repo doesn't have this problem, but whatever gets pushed up to azure is showing this.

**Comment by mathewc** [comment]
Yes, very strange. In both the dev and master branch of this repo, none of the versions of this script have this error. So it appears that the $ is being stripped somehow during the template deploy process. @soninaren?

**Comment by soninaren** [comment]
This is because of the way portal handles localization. It uses $ to know if the string is localized. But in the process it is removing $ from the string. This is a portal bug. It should not try and localize the code file. Also if it does not find a string it should leave $ in the front of the string as is.

**Comment by mathewc** [comment]
But the files on disk are also missing the $, so this is not merely a UI bug - the actual files are being corrupted. Why are you running localization on source files?

**Comment by soninaren** [comment]
Portal does it before hand when it converts templates to templates.json for showing and deploying tenplatest

**Comment by soninaren** [comment]
https://github.com/Azure/azure-webjobs-sdk-templates/commit/1c903b195e5063875434f2ee68a4c42b2fcea30f
