### ISSUE TITLE
Remove SaaSTable from bindings

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-templates#302]
Per conversations with @christopheranderson and Eduardo, we should remove SaaSTableTrigger from bindings.json (https://github.com/Azure/azure-webjobs-sdk-templates/blob/dev/Bindings/bindings.json#L559) and the sample here: https://github.com/Azure/azure-webjobs-sdk-templates/tree/dev/Templates/SaaSTable-CSharp

Reason: the current experience is sub-par.

**Comment by mathewc** [comment]
What are the issues? @emilcicos

**Comment by lindydonna** [comment]
@mathewc @emilcicos There's an email thread, I'll add you. It's complicated. :)

**Comment by soninaren** [comment]
Do you mean SaaS Table input binding. There is no SaaS Table trigger present.

**Comment by mathewc** [comment]
We're not doing this right now.
