### ISSUE TITLE
Rework "binding parameter name" label text

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-templates#307]
Moved from https://github.com/projectkudu/AzureFunctionsPortal/issues/569

From @mathewc:

Now that we support **$return** as a special binding mapping, the existing text doesn't make sense in such cases, since it is no longer a parameter:

![capture](https://cloud.githubusercontent.com/assets/1056548/18654250/67de4a9c-7e94-11e6-8b2f-2ed273a43702.PNG)

Perhaps we should just call this "binding name"?

**Comment by lindydonna** [comment]
@soninaren See if we can use an exclusivity rule to handle this

**Comment by soninaren** [comment]
Exclusivity rule would not be able to handle this scenario. 
We should have a checkbox saying use function return type. The checkbox should essentially add $return to function.json and grey-out or hide parameter name UI.

@lindydonna  or @christopheranderson  can you finalize the UI, portal would need to special case this.

**Comment by mathewc** [comment]
@soninaren Can you show me the UI when you finish? A checkbox might work.

**Comment by christopheranderson** [comment]
@soninaren - is this completed?

**Comment by lindydonna** [comment]
This isn't done because it needs design, moving to next milestone

**Comment by soninaren** [comment]
Binding.json: "SupportsReturnValue": true
Function.json:  "name": "$return"

**Comment by soninaren** [comment]
Moving this back to portal since it does not require any change in the templates repo.

**Comment by soninaren** [comment]
The new UI should be as follows, 
When you click the checkbox, the parameter name textbox should be disabled and $return should be set as the value for parameter name. This behavior should is applicable to all output bindings
![image](https://cloud.githubusercontent.com/assets/8119379/20504523/c318af94-affc-11e6-99e8-a400febe56a8.png)
