### ISSUE TITLE
PowerShell HttpTrigger should take parameters and output results, not use Content/IO

### ISSUE THREAD

**Issue by Jaykul** [Azure/azure-webjobs-sdk-templates#309]
I don't understand why the PowerShell methods have to `Get-Content $req` and `Set-Content $res` instead of having parameters and output, like the other languages?

```posh
param($req, $traceLogger)

<# ... do stuff #>
$name = $req.GetQueryNameValuePairs() | Where Name -eq "Name" | Select -Expand Value

return $req.CreateResponse("OK". "Hello $name");
```

**Comment by Jaykul** [comment]
If you were really going to be PowerShell friendly, you could handle the output of Write-Verbose and Write-Debug instead of passing the `$traceLogger`, and I suppose that you could hard-code the `$request` parameter ... but serializing both the request and the response feels _slow_ and convoluted.

**Comment by mathewc** [comment]
The first class PowerShell language support you're asking for is tracked in our runtime repo here: https://github.com/Azure/azure-webjobs-sdk-script/issues/337. Please add any feedback you have on the runtime model there, thanks.
