### ISSUE TITLE
Need to add more F# Templates

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-templates#310]
Currently we only have Empty and QueueTrigger samples for F#. We should expand this set to be at or near parity with our C# samples.

**Comment by lindydonna** [comment]
We're getting help from @dsyme and team!

**Comment by mathewc** [comment]
When?

**Comment by dsyme** [comment]
@mathewc We'll aim to have a PR done for at least some of these templates by the end of the week

**Comment by dsyme** [comment]
cc @sylvanc

**Comment by sylvanc** [comment]
PR #323

**Comment by lindydonna** [comment]
Closing since this has been merged. Thanks @sylvanc!
