### ISSUE TITLE
Remove System.Drawing code from Image Resize C# template

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-templates#312]
Since NuGet restore now works, remove these lines: 

https://github.com/Azure/azure-webjobs-sdk-templates/blob/dev/Templates/ImageResizer-CSharp/run.csx#L38-L46 
https://github.com/Azure/azure-webjobs-sdk-templates/blob/dev/Templates/ImageResizer-CSharp/run.csx#L38-L46

**Comment by soninaren** [comment]
Fixed here: https://github.com/Azure/azure-webjobs-sdk-templates/pull/356
