### ISSUE TITLE
Add support for "method" parameter in HttpTrigger integrate tab

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-webjobs-sdk-templates#317]
This should involve an exclusivity rule to allow for the default behavior (no configuration) versus a multi-selection of enumerable values. The method parameter itself is expressed as an array of strings in function.json.

The method selection control itself will be new as per https://github.com/projectkudu/AzureFunctionsPortal/issues/649.

Exclusivity rule label: "Allowed HTTP methods"
Exclusivity rule info balloon: "HttpTrigger can respond to any HTTP method. If you wish to restrict support to specific methods, choose the "Selected methods" option."
Exclusivity rule values: "All methods" (default case), "Selected methods"

Selected methods label: "Selected HTTP methods"
Selected methods Info balloon: "These are the only methods to which this function will respond."
Exclusivity rule values: "GET", "POST", "PUT", "DELETE", "OPTIONS", "HEAD", "PATCH", "TRACE"

![image](https://cloud.githubusercontent.com/assets/5815695/19251244/38d5f83e-8ef3-11e6-92b8-664d102dc0fa.png)

![image](https://cloud.githubusercontent.com/assets/5815695/19251240/2c93fdd2-8ef3-11e6-96dd-2ff87b6c5851.png)

**Comment by alrod** [comment]
My proposal:
{
					"name": "methods",
					"value": "checkBoxList",
					"defaultValue": [
						"get",
						"post",
						"delete",
						"head",
						"patch",
						"put",
						"options",
						"trace"
					],
					"enum": [
                        {
                            "value": "get",
                            "display": "GET"
                        },
                        {
                            "value": "post",
                            "display": "POST"
                        },
						{                    
                            "value": "delete",
                            "display": "DELETE"
                        },
						{                    
                            "value": "head",
                            "display": "HEAD"
                        },
						{                    
                            "value": "patch",
                            "display": "PATCH"
                        },
						{                    
                            "value": "put",
                            "display": "PUT"
                        },
						{
							"value": "options",
							"display": "OPTIONS"
						},
						{
							"value": "trace",
							"display": "TRACE"
						}						
					],
                    "label": "Methods",
                    "help": "Help methods"					
				}

**Comment by alrod** [comment]
[httpTrigger.txt](https://github.com/Azure/azure-webjobs-sdk-templates/files/540431/httpTrigger.txt)
