### ISSUE TITLE
Add "route" parameter to HttpTrigger integrate tab

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-webjobs-sdk-templates#318]
Label: "Route template"
Info balloon: "The route template setting allows you to change the URI that triggers this function. The values should be a relative path, starting with a slash '/'. Path segments may be treated as parameters by surrounding them with curly braces. For example: /customer/{customerId}"

![image](https://cloud.githubusercontent.com/assets/5815695/19251392/d7995b1e-8ef3-11e6-9227-9881246cfa1a.png)

**Comment by soninaren** [comment]
addressed in https://github.com/Azure/azure-webjobs-sdk-templates/commit/e4958640ae8752cbdc9d94e396f8312de8de4bc2
