### ISSUE TITLE
Use correct product names for Azure Storage bindings in Integrate tab

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-templates#319]
Azure Storage Queue -> Azure Queue Storage
Azure Storage Blob -> Azure Blob Storage
Azure Storage Table -> Azure Table Storage

**Comment by soninaren** [comment]
Fixed here
https://github.com/Azure/azure-webjobs-sdk-templates/commit/20dfa1b84d375feaa43c8aec2c233d17ff579aea
