### ISSUE TITLE
Create more complete templates with both input and output bindings

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk-templates#32]
Most current templates only have an input binding, making it hard for users to get up to speed. They can use UI to create output bindings, but then they're on their own with the code.

Some related discussions on https://github.com/Azure/azure-webjobs-sdk-script/issues/93.

**Comment by christopheranderson** [comment]
We have some ideas we're putting together in OneNote - we need to move it here anyway. @soninaren will take the lead in developing most of these after he's got some automation work done. @cfowler may also join in.

![image](https://cloud.githubusercontent.com/assets/2252976/13765669/afd4a1a4-ea18-11e5-9425-05f0c03ff6ca.png)

**Comment by soninaren** [comment]
Closing this one will open specific issue per template to be added.
