### ISSUE TITLE
Update names of bindings/templates to clearly distinguish release stages

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-webjobs-sdk-templates#320]
Need to update the bindings/templates with clear labels/categories for things that are released/preview/experimental.

## Release stages

Release:
- Supported and will stay backwards compatible within semver standards. Production use cases supported.

Preview:
- Close to release, but some compatibility issues may arise. Production use cases not recommended. Mostly committed to releasing this experience.

Experimental:
- Will likely have large changes. Expect breaking changes, even in patch versions. Absolutely do not use in Production workloads. Not necessarily committed to releasing this experience.
### Templates

All templates receive the lowest level of support specified. 

Example: if a template is using C# (Release) and SaaS File Triggers (Preview), it is preview, because Preview is the lowest support level.

Example: If a template is using Python (experimental) and Queue Trigger (Release), it is experimental, because experimental is the lowest support level.
### Integrate tab

In the portal, we should message if a binding is in a stage other than release (preview/experimental).
#### Release
- C#
- JS
#### Preview
- F#
- PowerShell
#### Experimental
- Batch
- Bash
- PHP
- Python
#### Release

| Service | Trigger | Input | Output |
| --- | --- | --- | --- |
| HTTP | ✓ |  | ✓* |
| Timer | ✓ |  |  |
| Manual | ✓ |  |  |
| Azure Blob Storage | ✓ | ✓ | ✓ |
| Azure Queue Storage | ✓ | ✓ | ✓ |
| Azure Table Storage |  | ✓ | ✓ | 
| Azure Service Bus [Queues + Topics] | ✓ |  | ✓ |
| Azure Event Hub | ✓ |  | ✓ |
| Azure DocDB |  | ✓ | ✓ |
| Azure Notification Hubs |  | ✓ |  |
| Azure Mobile Table |  | ✓ | ✓ |

(*) HTTP output response only used with HTTP Trigger request
#### Preview

| Service | Trigger | Input | Output |
| --- | --- | --- | --- |
| SaaS File* | ✓ | ✓ | ✓ |
| SendGrid |  |  | ✓ |
| Twilio SMS |  |  | ✓ |

(*) SaaS Files is being renamed to External Files soon
#### Experimental

| Service | Trigger | Input | Output |
| --- | --- | --- | --- |
| SaaS Table* |  | ✓ | ✓ |

(*) SaaS Table is being renamed to External Tables soon

**Comment by fabiocav** [comment]
Added SendGrid and Twilio to the list.

**Comment by christopheranderson** [comment]
Removed trigger from SaaS table

**Comment by soninaren** [comment]
fixed in https://github.com/Azure/azure-webjobs-sdk-templates/commit/0df02b9946d31117cef9d1f5e51828a2100bcdd2
