### ISSUE TITLE
Clean up SaaSTable-CSharp template

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-templates#325]
https://github.com/Azure/azure-webjobs-sdk-templates/blob/dev/Templates/SaaSTable-CSharp/run.csx#L29

This template has some extranous ; characters, as well as extra unecessary empty lines

**Comment by soninaren** [comment]
Fixed in this PR. https://github.com/Azure/azure-webjobs-sdk-templates/pull/360
