### ISSUE TITLE
SB output binding template should allow curly braces in queue name

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk-templates#329]
You can use curly braces in queue names -- but it's restricted in the portal.

![image](https://cloud.githubusercontent.com/assets/1089915/19653287/d0fa445a-99c8-11e6-8116-666ecc7c22d0.png)

**Comment by soninaren** [comment]
fixed in https://github.com/Azure/azure-webjobs-sdk-templates/pull/347
