### ISSUE TITLE
Add a default value for Table binding Take property

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-templates#352]
Related to core SDK issue https://github.com/Azure/azure-webjobs-sdk/issues/903. Once we decide on the default for that issue and apply it, we should also apply this same default in the binding template, so it is clear to users.

**Comment by lindydonna** [comment]
@soninaren please chat with @fabiocav on what is required here.

**Comment by mathewc** [comment]
This is related to https://github.com/Azure/azure-webjobs-sdk-templates/issues/340. I don't think we should add the default until after #340 is fixed, otherwise the default value we're putting into the file is of the wrong type (string rather than int).

**Comment by soninaren** [comment]
Fixed in PR https://github.com/Azure/azure-webjobs-sdk-templates/pull/358
The portal issue fix is in progress
