### ISSUE TITLE
Add a scenario that uses ConfigurationManager

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-webjobs-sdk-templates#353]
We broke ConfigurationManager in 1.0, we should test that it doesn't break later as well. Let's cover this in OGFs.

**Comment by mathewc** [comment]
Yes, use Configuration manager to load some app connection strings and app settings and verify values are returned. E.g.:

```csharp
    string conn = ConfigurationManager.ConnectionStrings["TestConnection"].ConnectionString;
    log.Info(conn);

    string setting = ConfigurationManager.AppSettings["TestSetting"];
    log.Info(setting);
```

**Comment by soninaren** [comment]
Have added an ogf for this.
