### ISSUE TITLE
$return Template change was rolled out too early

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-templates#354]
This commit https://github.com/Azure/azure-webjobs-sdk-templates/commit/69edece615cfd3c2181a54bafe465e2ca9f054c8 changed the default C# template to use $return but that only works in 1.0.

People on 0.9 versions of the runtime are getting this updated template and it is broken for them. See https://stackoverflow.com/questions/40590610/azure-functions-cannot-bind-parameter-return-to-type-httpresponsemessage. Is there something wrong with our template versioning scheme?

**Comment by soninaren** [comment]
I made an update to use $return that went to 0.9 and 1.0.

**Comment by soninaren** [comment]
https://github.com/Azure/azure-webjobs-sdk-templates/pull/355 fixes this

**Comment by soninaren** [comment]
Fixed in here https://github.com/Azure/azure-webjobs-sdk-templates/commit/13332af1778dd11fa6264d71569f6f3c00aab969
