### ISSUE TITLE
Update tooltip / help string for all binding.

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-webjobs-sdk-templates#387]
Help text for storage connections string is as follows
`This is the connection string for your storage account.`

Since visual studio tooling uses the strings from templates repository. Customers end up putting the actual connection string in the setting instead of appsetting name. We need to update the help/tooltip string so that it is applicable to both VS and portal.

**Comment by soninaren** [comment]
I have seen lot of issues like the one below
https://social.msdn.microsoft.com/Forums/en-US/978fe9e4-e573-48e3-a121-899ad3e8d3c0/microsoft-azure-webjobs-sdk-servicebus-connection-string?forum=AzureFunctions

**Comment by soninaren** [comment]
@lindydonna i need new strings for the tool tip that suits both portal and visual studio tooling

**Comment by paulbatum** [comment]
Ping @lindydonna
