### ISSUE TITLE
Include namespaces for classes used in templates

### ISSUE THREAD

**Issue by mathias-brandewinder** [Azure/azure-webjobs-sdk-templates#390]
Some templates use types such as `TraceWriter`, `TimerInfo`, or `ICollector<string>`, but the corresponding namespace is not included in the template - and it's not always obvious what the corresponding namespace is. As a result, when we open an F# (and I presume C#) function file in Code, we have errors and no Intellisense. 

I don't know if there was a technical reason for doing this, but would it make sense to include by default the namespaces for classes used in the template to avoid that issue? On the one hand, it would make the templates a bit heavier/longer; on the other hand, it would make editing function codes in Code (or other editors/IDEs) probably easier.

NB: I'd be happy to help out with the F# templates, if this is useful.

**Comment by lindydonna** [comment]
@fabiocav Do you have any objection to a PR that adds these namespaces for F#?  I believe you said that namespaces won't help C# intellisense?

**Comment by mathias-brandewinder** [comment]
I think I under-estimated the problem here, because the obvious namespaces are there in the templates (ex:  `System.Net.Http` is included when the trigger is an `HttpRequestMessage`), but when they aren't, it's not obvious what to do. If I understand correctly, there are 2 cases:
- the resource is implicitly included (ex: `TimerInfo`, `TraceWriter`)
- the resource is specified in the `project.json` file
In both cases, it seems that, when running locally, the function would "need to know" where to look for these resources on the local machine, and use nuget to grab then in that location if needed.
Can you clarify how you intend this to work in the longer term? Do you intend to support that use case, that is, opening and editing functions locally, with scripts that are not broken? 
I hope my questions make sense...

**Comment by lindydonna** [comment]
@mathias-brandewinder Exactly, it's not just a matter of adding the references, there also needs to be a hint path so that VS Code IntelliSense picks it up.

Longer-term, we plan to create a VS Code extension specifically for Functions IntelliSense. However, I don't have a timeline to share on that.

**Comment by lindydonna** [comment]
Closing this issue, since adding these namespaces won't actually fix IntelliSense. It sounds like the real request is IntelliSense for fsx files for Azure Functions in VS Code, and the right place to file that issue is here: https://github.com/Azure/Azure-Functions/issues 

Thanks!

**Comment by mathias-brandewinder** [comment]
Just adding a comment, which may be useful to others: adding
```
#I @"C:\Users\Mathias\AppData\Roaming\npm\node_modules\azure-functions-cli\bin"
#r "Microsoft.Azure.WebJobs.Host.dll"
open Microsoft.Azure.WebJobs.Host
```
... at the top of my script helps fix a lot of intellisense issues, because this now points at the location where all the "magic dlls" are installed. This will not handle the issue of additional nuget packages pulled via project.json, but it is an improvement over the raw template if I want to be productive locally.

**Comment by lindydonna** [comment]
@mathias-brandewinder Btw, you might be able to generalize that path to `%USERPROFILE%\AppData...`, but I haven't tested it.
