### ISSUE TITLE
Remove discrepancy between query string token in plain http vs WebHook

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk-templates#4]
Currently, WebHooks use `code=...` (coming from WebHook SDK), while plain http use `key=...` (coming from our own logic).

One way or another, let's find a way to make them be the same.

**Comment by mathewc** [comment]
This probably belongs in the script repo. I'm planning on creating a pull request against the WebHooks SDK to make it configurable. I investigated but didn't want to do url rewrite on our side, because the SDK error messages would still mention 'code' which would confuse our users.

**Comment by davidebbo** [comment]
Darn, that's where I meant to put it!

**Comment by davidebbo** [comment]
https://github.com/Azure/azure-webjobs-sdk-script/issues/61. Go ahead and copy your comment there :)
