### ISSUE TITLE
Errors in Blob path UI and Regex Validation

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-templates#409]
_From @mathewc on February 11, 2017 17:42_

2 issues. First, our blob path regex is overly restrictive. Second, the actual help text isn't resolving. Path expressions can contain an arbitrary number of path segements, and each supports {} binding expressions. Note also that %% expressions are also supported (binding from app settings, e.g. %MY_CONTAINER%/{Foo}/{Bar}). We should review all our regexes and make sure they're correct in this regard.

![image](https://cloud.githubusercontent.com/assets/1056548/22856012/54404a50-f03e-11e6-9610-eeb4973a5cc4.png)

_Copied from original issue: projectkudu/AzureFunctionsPortal#911_

**Comment by lindydonna** [comment]
_From @mathewc on February 11, 2017 17:45_

@soninaren

**Comment by soninaren** [comment]
Fixing the regex so that it accept the following inputs, Fixing regex for storage bindings, opening a new issue to review all other regexs
```
con/a
{container}/{a}
%abc%/{a}/{ab}/a
%abc%/%a%/{abc}/a
{Container}/{first}
con/{a}
```

Also for blob trigger it accept the following as well
```
con
{Container}
{container}
%abc%
```
