### ISSUE TITLE
Fix DocumentDb output binding display name

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-webjobs-sdk-templates#413]
DocumentDb output binding display name should be: $documentDBOut_displayName
More details at:  [Serverless Plugin issue](https://github.com/serverless/serverless-azure-functions/issues/36)

**Comment by soninaren** [comment]
Changing the display name would have no visible effect in the portal. Not sure how it will resolve the serverless plugin issue. Have updated for consistency.

**Comment by soninaren** [comment]
#492
