### ISSUE TITLE
CommandNotFoundException

### ISSUE THREAD

**Issue by psmith6** [Azure/azure-webjobs-sdk-templates#435]
I have a function that I created using the App Service Editor. When I test and debug with the editor everything works correctly. When I try to trigger the function using HTTP, I get the CommandNotFoundException for all of the cmdlet below.

- Login-AzureRmAccount
- Remove-AzureRmWebAppSlot 
- Remove-AzureRmWebApp
- Remove-AzureRmSqlDatabase
- Remove-AzureRmStorageAccount
- New-AzureRmWebApp 
- New-AzureRmSqlDatabase 
- New-AzureRmStorageAccount

**Comment by lindydonna** [comment]
This question is a better fit for the MSDN forums. Could you please post on https://aka.ms/func-forum?
