### ISSUE TITLE
defaultFunctionName Text gets out of the border

### ISSUE THREAD

**Issue by davidlai-msft** [Azure/azure-webjobs-sdk-templates#440]
While trying to create a new template, noticed the following...

![image](https://cloud.githubusercontent.com/assets/10729539/25592865/39f78c3e-2e6f-11e7-9612-58f142d35692.png)

And the followings...

![image](https://cloud.githubusercontent.com/assets/10729539/25594680/82469762-2e76-11e7-98a8-c5d038de76e2.png)

Thanks,
David

**Comment by soninaren** [comment]
moved to https://github.com/projectkudu/AzureFunctionsPortal/issues/1285
