### ISSUE TITLE
Add support for customized Categories

### ISSUE THREAD

**Issue by davidlai-msft** [Azure/azure-webjobs-sdk-templates#441]
Currently categories are limited to these:
![image](https://cloud.githubusercontent.com/assets/10729539/25596833/24b1b71c-2e80-11e7-87e1-5929ee54f1a7.png)

Adding support for custom categories can enable us to group product related templates to product category and can avoid the need to append product name in front of the template name.

For instance, ApplicationInsightsScheduledAnalytics can be reduced to just ScheduledAnalytics under Application Insights category.

**Comment by soninaren** [comment]
moved to https://github.com/projectkudu/AzureFunctionsPortal/issues/1284
