### ISSUE TITLE
Queue template requires new storage connection

### ISSUE THREAD

**Issue by mamaso** [Azure/azure-webjobs-sdk-templates#449]
Should be able to choose `AzureWebJobsStorage` or `AzureWebJobsDashboard` as connection, as in Blob templates

This may be an issue with the functions portal, not sure exactly

**Comment by soninaren** [comment]
Can you add repro steps? I am able to select the storage connection

![image](https://cloud.githubusercontent.com/assets/8119379/25926349/919604da-35a3-11e7-880e-e94a8d7ac13f.png)

**Comment by mamaso** [comment]
Unable to repro as well, thanks for looking into this!
