### ISSUE TITLE
Azure Functions Portal UX - Dead Letter Queue (DLQ) Name Doesn't Pass Validation

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-templates#450]
_From @slideep on May 12, 2017 12:48_

Not quite sure to which repo to report this but queue name being dead letter queue fails miserably validation - though, it's perfectly valid queue name! At least the function works and triggers as expected.
![az_functions_portal_ux_dlq_validation](https://cloud.githubusercontent.com/assets/100609/25998550/30d66bac-372a-11e7-8567-8e6a289c488f.PNG)

_Copied from original issue: Azure/Azure-Functions#282_

**Comment by lindydonna** [comment]
_From @ahmelsayed on May 12, 2017 21:9_

/cc @alrod and @soninaren 

I think it should go [here](https://github.com/Azure/azure-webjobs-sdk-templates/) where we keep the regex used to validate UX input.

**Comment by lindydonna** [comment]
_From @mwitlok on May 13, 2017 20:43_

The same is true of the "Subscription name"-field when creating a Topic/Subscription trigger.

**Comment by soninaren** [comment]
Fixed here
https://github.com/Azure/azure-webjobs-sdk-templates/commit/f0ea83e500f063419b60941614a38a6d43b19360
