### ISSUE TITLE
Support for .Net Core

### ISSUE THREAD

**Issue by BillRaymond** [Azure/azure-webjobs-sdk-templates#470]
Not sure if I am publishing this to the correct location, but I did want to request that Azure Functions templates support .Net Core, especially given that they are very similar to Web APIs, which do support .Net Core. Thanks.

**Comment by lindydonna** [comment]
We're working on porting the runtime to .NET core. When we do, we'll update the templates. That work is tracked by https://github.com/Azure/Azure-Functions/issues/98

**Comment by BillRaymond** [comment]
Cool. Good to hear. Thanks.
