### ISSUE TITLE
TypeScript Declarations for TypeScript templates

### ISSUE THREAD

**Issue by mike-morr** [Azure/azure-webjobs-sdk-templates#477]
Where do I get the TS Declarations so I don't need to type everything as any?

**Comment by lindydonna** [comment]
Are you asking for the typings file?  CC @christopheranderson

**Comment by christopheranderson** [comment]
I've got a prototype here: https://github.com/christopheranderson/azure-functions-typescript

I'll probably be cleaning it up soon for an initial release. Ideally we move to auto-generate this from our Node.js code itself, before we'd "GA" the typings.

**Comment by mike-morr** [comment]
I'll take a look at the prototype, thank you!
