### ISSUE TITLE
Bug in Python samples in Functions

### ISSUE THREAD

**Issue by smereczynski** [Azure/azure-webjobs-sdk-templates#485]
When we are creating Python sample app from Azure portal, we have an information that it is a Python 3 app:

![image](https://user-images.githubusercontent.com/705653/27703872-0f6264e4-5d09-11e7-889b-673c5f57a84d.png)

But after we create it and run, it's clear that it is Python 2.7 app:

![image](https://user-images.githubusercontent.com/705653/27703897-23c751e2-5d09-11e7-90ce-82b65cde1a3e.png)

**Comment by lindydonna** [comment]
Fixed by @paulbatum.
