### ISSUE TITLE
Remove the runtime package references from the template

### ISSUE THREAD

**Issue by vijayrkn** [Azure/azure-webjobs-sdk-templates#507]
Remove the following runtime package references from the template:

    <PackageReference Include="Microsoft.Azure.WebJobs" Version="2.1.0-beta1" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="2.1.0-beta1" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Http" Version="1.0.0-beta1" />
    <PackageReference Include="Microsoft.Azure.WebJobs.ServiceBus" Version="2.1.0-beta1" />
    <PackageReference Include="Newtonsoft.Json" Version="9.0.1" />

These package references will be part of Microsoft.NET.Sdk.Functions

**Comment by paulbatum** [comment]
See related: https://github.com/Azure/azure-functions-vs-build-sdk/issues/75. Need both of these.
