### ISSUE TITLE
Allow bindings to be categorized (specifically into an 'experimental' category)

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk-templates#51]
Some bindings won't behave the same when used in node vs when used in C#. It'd be nice if we could restrict a binding to supported languages until they're updated, tested, and verified.

**Comment by mathewc** [comment]
Having a setting like that is dangerous I think - it could lead to us saying some bindings don't work across languages, which we don't want. What binding are you referring to specifically that doesn't work in Node?

Can't we just use the existing "experimental" category to classify templates that aren't yet working?

**Comment by brettsam** [comment]
This issue: https://github.com/Azure/azure-webjobs-sdk-script/issues/107.

This means that C# `in` bindings will update the changes to the object when it exits (it's effectively `inout` but C# doesn't care about what you specify on the binding). But in node it will only act as `in` and any changes you make in the function do not get sent along.

My guess is we'll bump into other things like this in the future and it's nice to be able to restrict behavior. In this example, I'd rather be able to say -- if you're using `in`, then you need C# right now.

I don't think you can classify bindings as experimental -- that's just for templates.

**Comment by fabiocav** [comment]
I'm with @mathewc on this one. I'd rather see bindings placed in an "experimental" category than showing up as production ready if there are discrepancies of different support depending on the features you're using.

**Comment by brettsam** [comment]
Okay -- I've updated the title.

**Comment by mathewc** [comment]
I don't think we should categorize bindings in this way. We have bugs and we'll fix them, but the goal is that any binding we release templates for works across languages, with a few templates for each. There will be some differences across languages (there are other examples outside of this in/out issue). That's ok and expected I think.

**Comment by alrod** [comment]
Portal change is done. example of using:
        {
            "type": "eventHubTrigger",
            "displayName": "Azure Event Hub",
            "direction": "trigger",
            "defaultParameterName": "myEventHubMessage",
            "parameterNamePrompt": "Event parameter name",
            "settings": [
                {
                    "name": "path",
                    "value": "string",
                    "defaultValue": "myEventHub",
                    "required": true,
                    "label": "Event Hub name",
                    "help": "This is the name of the Event Hub you would like to trigger off of.",
                    "validators": [
                        {
                            "expression": "^[A-Za-z0-9]$|^[A-Za-z0-9][\\w-\\.\\/]*[A-Za-z0-9]$",
                            "errorText": "Invalid event hub name"
                        }
                    ]
                },
                {
                    "name": "connection",
                    "value": "string",
                    "resource": "EventHub",
                    "required": true,
                    "label": "Event Hub connection",
                    "help": "This is the connection string for your Event Hub. Make sure that it has Receive permissions."
                }
            ],
**			"filters": ["testf"]**
        },

https://functions.azure.com/?testf=1

**Comment by fabiocav** [comment]
@alrod is this really the issue you wanted to reference?

**Comment by soninaren** [comment]
#174 fixes this. Have hidden api hubs binding.
