### ISSUE TITLE
Incorrect connection for imageMedium binding of ResizeImage template

### ISSUE THREAD

**Issue by SimonGuo009** [Azure/azure-webjobs-sdk-templates#523]
**Environment Info**:
![environmentinfosmall](https://user-images.githubusercontent.com/18321627/29210518-8bfe2e1e-7ec6-11e7-98d9-b6cbfdb851ac.jpg)

**Expected result**:
Connection should recieve the value user entered. 
**Actual result**:
For binding _imageMedium_, it have same value with Path.

Please refer to snapshot:
![sampleimageconnectionincorrect](https://user-images.githubusercontent.com/18321627/29210618-ee3c2c48-7ec6-11e7-8117-161cf4537a15.JPG)

**Comment by soninaren** [comment]
Fixed here https://github.com/Azure/azure-webjobs-sdk-templates/commit/7b4195919939ae1c600d22b69a601e892094d280
