### ISSUE TITLE
ResizeImage template run into error while running locally

### ISSUE THREAD

**Issue by SimonGuo009** [Azure/azure-webjobs-sdk-templates#524]
**Environment Info**:
![environmentinfosmall](https://user-images.githubusercontent.com/18321627/29210518-8bfe2e1e-7ec6-11e7-98d9-b6cbfdb851ac.jpg)

**Expected result**:
ImageSmall binding have similar configuration with imageMedium, it should work well like imageMedium.
**Actual result**:
ImageSmall binding got error message. Please refer to snapshot:
![resizeimageerror](https://user-images.githubusercontent.com/18321627/29210740-8775ac7c-7ec7-11e7-8455-8500e90b28a0.JPG)

**Comment by soninaren** [comment]
Fixed here https://github.com/Azure/azure-webjobs-sdk-templates/commit/7b4195919939ae1c600d22b69a601e892094d280
