### ISSUE TITLE
Allow a template to specify required binding extensions

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-webjobs-sdk-templates#537]
Templates should be able to pull in any extensions that they require. This would need to be defined in the template metadata, and when the user goes to create a function, the extensions are added to their function app.

Note that if the UX is being derived from (as proposed in https://github.com/Azure/azure-functions-ux/issues/1698), then the extension would actually have to be in place before we can paint the properties.

That may mean we need a multi-step process in the UX. After selecting a template:
- (If you don't have any of the required extensions) See a warning that it details what extensions the template requires that you don't have. Click a button to install the extensions and continue.
- See the template UX as normal.

If we want to go with that plan, we may need to create a work item in the UX repo for the multi-step process. There may be other solutions to this problem, though.

**Comment by lindydonna** [comment]
Is this for @soninaren?

**Comment by mattchenderson** [comment]
Likely, yes.
