### ISSUE TITLE
Allow authentication metadata to be included in bindings and templates

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-webjobs-sdk-templates#538]
A binding, as part of its metadata, should declare if it uses authentication, including the type and what permissions (if any) it needs.

Similarly, a template should declare the same. This should be an aggregation of the included bindings, as well as any additional requirements introduced by the template code.

That means in both cases, we need an explicit metadata field, although the UX will need to act on more than that in the case of templates.

**Comment by mattchenderson** [comment]
There is also the open question of if auth-related UX should be handled with a special metadata flag, or if it should be considered a normal set of properties for a binding. This is particularly important for extensions, which may derive from one another and assume some properties to be configured, such as auth config. Should those properties and UX just be inherited? Or is a special flag needed (and maybe that's what's inherited)?

**Comment by lindydonna** [comment]
@mattchenderson Is this for @soninaren?

**Comment by mattchenderson** [comment]
Likely, yes. We've talked about it a bit.
