### ISSUE TITLE
Allow templates to expose an exclusivity rule for auth config

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-webjobs-sdk-templates#541]
We want templates to have the exclusivity rules, which can be used for auth config that bindings will have.

@soninaren has additional context

**Comment by soninaren** [comment]
This is done

**Comment by soninaren** [comment]
https://github.com/Azure/azure-webjobs-sdk-templates/commit/c541445575996c834eb05354fc3708684124ea81
