### ISSUE TITLE
Inconsistent behaviour when creating a KeyVault key via an Azure PowerShell Function

### ISSUE THREAD

**Issue by adamwebbcollabware** [Azure/azure-webjobs-sdk-templates#544]
When attempting to create a KeyVault key via an Azure PowerShell Function I am experiencing inconsistent behaviour. It seems that running identical PowerShell on different function hosts will return different results/failures. The failure is a variant of the following:

_Get-AzureRmKeyVault : Your Azure credentials have not been set up or have expired, please run Login-AzureRmAccount to set up your Azure credentials.

The script is designed to authenticate to Azure via an Azure AD service principal, get the relevant KeyVault and create a key within it. But, even when hard-coding all the values for troubleshooting, the inconsistency still exists across differing function hosts i.e. one creates a KeyVault key successfully, whereas the other fails.

`$ServicePrincipalPassword = ConvertTo-SecureString "password" -AsPlainText -Force 
$ServicePrincipalCredential = New-Object System.Management.Automation.PSCredential ($ServicePrincipalAppId, $ServicePrincipalPassword) 
$Login = Login-AzureRmAccount -ServicePrincipal -TenantId $TenantId -Credential $ServicePrincipalCredential 

$KeyVault = Get-AzureRmKeyVault -VaultName "testkeyvault"
write-output "$($KeyVault.VaultURI)"

$Key = Add-AzureKeyVaultKey -VaultName $KeyVault.VaultName -Name 'testkey' -Destination Software
$KeyUrl = $Key.id.Substring(0, $Key.id.LastIndexOf("/"))
Write-Output $KeyUrl`

Is this behaviour expected or anything I can do to make the experience consistent?

Thanks.

**Comment by ahmelsayed** [comment]
closing in favor of https://github.com/Azure/azure-webjobs-sdk-script/issues/1827. Please avoid double posting.
