### ISSUE TITLE
Fix text on JS EventGrid function template

### ISSUE THREAD

**Issue by simonaco** [Azure/azure-webjobs-sdk-templates#545]
Javascript event grid function template shows C# in description. 

<img width="483" alt="screen shot 2017-08-23 at 22 24 33" src="https://user-images.githubusercontent.com/1573904/29677762-150cb59a-88f4-11e7-92ea-c63f8f4fbd96.png">

**Comment by soninaren** [comment]
Fixed in this commit https://github.com/Azure/azure-webjobs-sdk-templates/commit/a320bc8fadaa8f9726ccbc0eccb796fa65d18995
