### ISSUE TITLE
Remove Python and PHP templates from 2.0 repo

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-webjobs-sdk-templates#550]
Until we have a proper out-of-proc implementation for python and php, these templates should not appear for functions v2 apps. Delete the templates (from v2 branch) until then.

**Comment by soninaren** [comment]
We only have the following templates in the v2 branch

BlobTrigger-CSharp
EventGridTrigger-CSharp
HttpTrigger-CSharp
HttpTriggerWithParameters-CSharp
QueueTrigger-CSharp
TimerTrigger-CSharp
