### ISSUE TITLE
Rename trigger 'input' parameter to 'documents'

### ISSUE THREAD

**Issue by ggailey777** [Azure/azure-webjobs-sdk-templates#576]
https://github.com/Azure/azure-webjobs-sdk-templates/blob/6094a10e330b8e492088b23f7148e7b2aa96397d/Functions.Templates/Templates/CosmosDBTrigger-CSharp/CosmosDBTriggerCSharp.cs#L24

We've seen confusion with the `input` parameter of the Cosmos DB trigger. Customers were confusing it with a Cosmos DB input binding. Can't we just rename this to `documents`?

**Comment by paulbatum** [comment]
@ealsur this looks like a reasonable rename to me.. if you agree do you want to submit a tiny PR for this?
