### ISSUE TITLE
The python function script is not reachable from the web browser 

### ISSUE THREAD

**Issue by tinkur1** [Azure/azure-webjobs-sdk-templates#579]
When I copy the function url and try it on the web browser, I am not able to reach the python script

**Comment by baizini** [comment]
I have exactly the same issue

**Comment by paulbatum** [comment]
When you use the URL in your web browser, you are creating a GET request. The python template is configured to accept a POST request. See https://github.com/Azure/azure-webjobs-sdk-templates/issues/543#issuecomment-348098397.
