### ISSUE TITLE
Azure Functions SDK not able to integrate with Azure Cosmos DB Tables

### ISSUE THREAD

**Issue by sanket-t-shah** [Azure/azure-webjobs-sdk-templates#582]
Hi,
Am trying to integrate Azure Functions with Cosmos DB Tables, but it's failing. I've opened a separate conversation with Cosmos DB Team and it was flagged as an issue with Azure Functions SDK as the namespaces are same in Azure Functions SDK and Cosmos DB Premium Tables.
Please help to resolve the issue.

Just to add more - am using C# scripts and VS Studio templates for writing code.

**Comment by sanket-t-shah** [comment]
Is there any update on this?

**Comment by paulbatum** [comment]
This is not a template issue. The premium tables + functions scenario is tracked by https://github.com/Azure/azure-webjobs-sdk-script/issues/1751
