### ISSUE TITLE
Can I use PowerShell with CosmosDB?

### ISSUE THREAD

**Issue by aarsan** [Azure/azure-webjobs-sdk-templates#586]
I am trying to write a PowerShell Function that is triggered by CosmosDB. The trigger works fine but the variable passed in ($inputDocs) seems to resolve to: 

    "D:\local\Temp\Functions\Binding\98d27d01-da2f-4137-b3b8-3765816f21c4\inputDocs" 

In the JavaScript and C# examples, $inputDocs[0].id should return the doc ID but this does not work in PowerShell. Am I using an unsupported language? There is no PowerShell example for a CosmosDB trigger. 

thanks!

**Comment by aarsan** [comment]
Also, is there a place I can read about the specifics of how these triggers work?

**Comment by itpropro** [comment]
You have to use Get-Content to get content. You will always get the whole content of every document in the referrenced collection, when you use PowerShell.

**Comment by paulbatum** [comment]
Closing this issue as we do not plan on adding a powershell+cosmos template at this time.
