### ISSUE TITLE
Microsoft.ServiceBus.Messaging is missing

### ISSUE THREAD

**Issue by seancpeters** [Azure/azure-webjobs-sdk-templates#597]
From the original bug: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/Web%20Tools/_workitems?id=496109&_a=edit

Just created a new Azure Functions Project in VS15.3.4: - BlobTrigger works without problems - Immediately after creating a Function triggered by Azure ServiceBus Queue, the following error appears:
https://developercommunity.visualstudio.com/content/problem/113092/azure-functions-microsoftservicebusmessaging-is-mi.html
To find diagnostic information, see the original linked feedback ticket: https://devdiv.visualstudio.com/DevDiv/_workitems?id=494636&_a=edit

In the original Developer Community issue, the user stated: "After including the Nuget package pre-release version of Microsoft.Azure.WebJobs.ServiceBus 2.1.0-beta1 it worked again!"

So getting that package to restore from the template is probably all that's needed.

**Comment by soninaren** [comment]
Package restore is already part of the template. 
https://github.com/Azure/azure-webjobs-sdk-templates/blob/dev/Functions.Templates/Templates/ServiceBusQueueTrigger-CSharp/build.config/template.json#L57-L68

It could be that he user is on a version of templates where the package wasn't a part of the restore. May an update to functions extension would fix the issue for the user.

**Comment by AlissonRS** [comment]
I'm facing this very same issue. Just created a template project, and it fails to compile because `Microsoft.ServiceBus.Messaging` is missing.
