### ISSUE TITLE
[Help Wanted] How to generate templates for portal

### ISSUE THREAD

**Issue by jdneo** [Azure/azure-webjobs-sdk-templates#598]
Hi team, 

I followed the build guide in the [repo home page](https://github.com/Azure/azure-webjobs-sdk-templates#generate-templates-for-portal) but meet some problems.

- I cannot find ```Azure.Functions.Templates.Portal``` folder under ```functions.Templates\bin\Portal\Release\```, but ```Azure.Functions.Ux.Templates```
- I cannot find ```Test``` under ```Functions.Templates\bin\Portal\```.
- Cannot find ```templates.json``` in the ```bin``` folder

I'm using VS2017 Community, and build the project by clicking ```Build Functions.Templates```:
![image](https://user-images.githubusercontent.com/6193897/32591072-a033c19a-c558-11e7-8f13-283dad61b19e.png)

Is that because I did the wrong build process?

Thanks.

**Comment by soninaren** [comment]
The build was recently updated and the documentation is slightly behind. The folder name has been changed to Azure.Functions.UX.Templates. 
Do you see any build errors?
What do you see under Azure.Functions.UX.Templates? The templates should be under Azure.Functions.UX.Templates\templates.

**Comment by soninaren** [comment]
For test bits you would need to execute the following command from functions.templates folder
` msbuild Functions.Templates.csproj /target:TestConfig`

**Comment by jdneo** [comment]
Hi @soninaren, templates can be shown under Azure.Functions.UX.Templates\templates on my side.

And after trying the test build command, I got ```bindings.json``` and ```templates.json``` successfully.

Problems solved and thanks for the timely reply.
