### ISSUE TITLE
Trouble with blob bindings in Powershell Azure Functions

### ISSUE THREAD

**Issue by rabrahamOpti** [Azure/azure-webjobs-sdk-templates#603]
I'm trying write an Azure TimerTrigger function in Powershell that accesses a blob I tried to bind to the function via the function.json file. That file looks like this:

    {
      "bindings": [
        {
          "name": "myTimer",
          "type": "timerTrigger",
          "direction": "in",
          "schedule": "0 */5 * * * *"
        },
        {
          "type": "blob",
          "name": "OutBlob",
          "path": "my-container-name/my_blob_filename.txt",
          "connection": "AzureWebJobsStorage",
          "direction": "out"
        },
        {
          "type": "blob",
          "name": "InBlob",
          "path": "my-container-name/my_blob_filename.txt",
          "connection": "AzureWebJobsStorage",
          "direction": "in"
        }
      ],
      "disabled": false
    }

I see OutBlob and InBlob listed as variables when I run
    
    Get-Variable | Select Name,Value
    
from within the TimmerTriggerFunction. Here's the output:
    
    @{Name=InBlob; Value=D:\local\Temp\Functions\Binding\{GUID}\InBlob}2017-11-17T20:27:21.943 
    @{Name=OutBlob; Value=D:\local\Temp\Functions\Binding\{GUID}\OutBlob}2017-11-17T20:27:21.943
    
But they seem to be of type System.String rather than Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.

At least, that's the result I get when I run:
    
    $InBlob.GetType()
    
I get an exception when I try the following
    
    [Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob]$InBlob.GetType()

The exception reads as follows:
    
    2017-11-17T21:03:14.542 : Cannot convert the "System.String" value of type "System.RuntimeType" to type "Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob".

Is there a problem with the binding? Or am I doing this wrong?

**Comment by soninaren** [comment]
This question is a better fit for the MSDN forums as it is not a bug in templates and would potentially help other developers in a similar situation.
Could you please post on https://aka.ms/func-forum?

**Comment by rabrahamOpti** [comment]
Hi @soninaren I'm having trouble logging into the MSDN forums. I'll post the question there ASAP, but could you let me know what's wrong here? If another developer finds this issue via a Google search, it'd be nice to have it documented here as well. Thanks!

**Comment by rabrahamOpti** [comment]
@soninaren I got a response informing me that "PowerShell Functions only support string inputs today". If this is true, then I shouldn't be able to define a blob binding in powershell function's function.json config file. If Chris Anderson's statement is true, this is a bug and this issue should be reopened.

**Comment by soninaren** [comment]
PowerShell does support blob binding which makes function.json is valid. To clarify my previous comment, this is still not a bug in any of PowerShell templates present in this code repository. The only thing is that you will only be able to fetch useful data from string blob when using blob bindings via PowerShell. 

So for your function.json valid code file would be 

```
$in = Get-Content $InBlob -Raw
Write-Output "PowerShell script processed blob '$in'"
$InBlob | Out-File $OutBlob 
```

Lastly, i see an error in function.json your input and output blob and container are same. This would basically mean you are reading from and writing to the same blob, causing a continuous flurry of executions.

Here is a sample of working table storage output binding using PowerShell
https://stackoverflow.com/questions/44910406/how-to-read-from-azure-table-storage-with-a-http-trigger-powershell-azure-functi/44911521#44911521
