### ISSUE TITLE
PS Function Writing to Log Streaming Service

### ISSUE THREAD

**Issue by injector22** [Azure/azure-webjobs-sdk-templates#608]
Maybe I'm blind but is there a way to write to the log streaming service when writing in PowerShell? it would be great to have a way to debug incoming triggers.

**Comment by injector22** [comment]
I did some further testing and it looks like at some point 

> [Console]::WriteLine("");

Used to work, but now it no longer works.

**Comment by soninaren** [comment]
you can use 
```
Write-Output ""
```

**Comment by soninaren** [comment]
In future can you post a non-bug related issues/questions to [https://aka.ms/func-forum](https://aka.ms/func-forum) or [https://stackoverflow.com/questions/tagged/azure-functions](https://stackoverflow.com/questions/tagged/azure-functions)
