### ISSUE TITLE
Missing cmdlets needed for creating new VMs

### ISSUE THREAD

**Issue by pollardsg** [Azure/azure-webjobs-sdk-templates#614]
Following seem to be missing cmdlets in my App Service powershell function:
New-AzureRmDiskConfig 
New-AzureRmDisk
New-AzureRmVirtualNetwork
New-AzureRmVirtualNetworkSubnetConfig 
New-AzureRmNetworkSecurityRuleConfig
New-AzureRmNetworkSecurityGroup
New-AzureRmPublicIpAddress
New-AzureRmNetworkInterface

Is there a reason they are not available?

**Comment by pollardsg** [comment]
For example I'm getting the following error:
New-AzureRmDisk : The term 'New-AzureRmDisk' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
at run.ps1: line 74

**Comment by soninaren** [comment]
This is not right repository for this issue. This repository contains templates for [Azure Functions](https://azure.microsoft.com/en-us/services/functions/). I think the repository you are looking for is this one [Azure Powershell](https://github.com/Azure/azure-powershell).

**Comment by soninaren** [comment]
Misquoted the repository. Moving to the correct repository. https://github.com/Azure/azure-webjobs-sdk-script/
