### ISSUE TITLE
Service Bus bindings need work

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-webjobs-sdk-templates#68]
1. There is a binding labelled "Service Bus" which is quite ambiguous (if its for service bus queues it should be labelled as such). 
2. The picker for a service bus queue should not be asking you to select a notification hub. These need to be different pickers!
3. The label for the queue name box is "Which queue would you like to trigger off of" -- but you're not triggering, you're creating messages in this queue.

**Comment by soninaren** [comment]
For
1. We have a separate issue tracking #134 
2. Filed issue on portal for this #329
3. This has been addressed
