### ISSUE TITLE
Issue with webhook binding type "generic"

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-webjobs-sdk-templates#78]
There is no such thing as webhookType: "generic". The drop down should instead have an option that says "Generic JSON" and this should correspond to webhookType: "genericJson".

**Comment by mathewc** [comment]
I'll fix this in my open template PR

**Comment by mathewc** [comment]
I'll fix this in my open template PR

**Comment by mathewc** [comment]
https://github.com/Azure/azure-webjobs-sdk-templates/pull/79

**Comment by mathewc** [comment]
Fixed with https://github.com/Azure/azure-webjobs-sdk-templates/commit/e95dc94fc50abff856ada152d73b01eb065b43c3
