### ISSUE TITLE
EventHub Trigger example for C#

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-webjobs-sdk-templates#81]
We need a template for Event Hub Trigger C#

**Comment by davidebbo** [comment]
A demo meaning a template?

**Comment by christopheranderson** [comment]
Yes. Updated my original comment text. :)

**Comment by paulbatum** [comment]
@fabiocav Maybe you could knock this out really quick?

**Comment by fabiocav** [comment]
:+1:
