### ISSUE TITLE
Service Bus Trigger for C# and promote Node & C# to Core

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-webjobs-sdk-templates#82]
## Issue
Service Bus Trigger template for C# doesn't exist and the Node version is in experimental

## Recommended fix

0. Add a template for Service Bus Trigger C#
0. Promote the Node & C# templates to Core scenario

**Comment by mathewc** [comment]
If we're investing in more SB templates, then perhaps we should promote them from "Experimental" as well? SB support has been around a LONG time and is much more stable than the new EventHub binding which is not listed as experimental.

**Comment by christopheranderson** [comment]
Agreed. Updated issue.

**Comment by paulbatum** [comment]
Moved to backlog, we're removing service bus for build

**Comment by soninaren** [comment]
#143 address this
