### ISSUE TITLE
[Table Binding] - template has invalid setting for partition key

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-webjobs-sdk-templates#84]
## Issue

The input object for "partition key" is invalid. Currently `{project-id}`. Receive this error when used: `Invalid template '{project-id}'. The parameter name 'project-id' is invalid.`

**Comment by paulbatum** [comment]
@christopheranderson is this JS specific?

**Comment by yochay** [comment]
No it is also in C#

should be {partition}
