### ISSUE TITLE
JS queue trigger template has confusing .id reference

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-webjobs-sdk-templates#89]
The template has this code:

```
module.exports = function (context, myQueueItem) {
    context.log('Node.js queue trigger function processed work item', myQueueItem.id);
    context.done();
};
```
The confusing thing is that this .id reference is not referring to the actual azure queue id of the message.. its based on the sample data having an ID property.

To make this sample less confusing, lets change the sample data to something else.

**Comment by mathewc** [comment]
Yes it does lead to confusion, because if the payload doesn't include and id property, there is actually the ambient queue message Id property that already exists in the binding context. So in the example above, you can bind to either `id` or `Id`.

**Comment by paulbatum** [comment]
I'm about to send a PR to make this template consistent with the C# one and address this issue

**Comment by mathewc** [comment]
I was trying to demonstrate the fact that the input is an object - that's why the original samples had an id property used in the script. Similar to the current Node blob sample which also accesses .id.
