### ISSUE TITLE
Allow entering MobileApp uri directly in the EasyTable binding ui

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-webjobs-sdk-templates#95]
Right now only app setting is allowed for specifying MobileApp Uri:
What is the app setting that specifies the URL of your Mobile App?  

We should accept url directly as it is not a secret.

**Comment by mathewc** [comment]
Make sure there are no other secrets in this binding.

**Comment by christopheranderson** [comment]
I think the way this should work is just like any of our data connectors work today - it should be a picker. So let's keep the app setting model, but I'm filing an issue for the portal to support the Mobile App picker.

Portal issue:
https://github.com/projectkudu/AzureFunctionsPortal/issues/328
