### ISSUE TITLE
Cron Trigger expressions not supported 

### ISSUE THREAD

**Issue by fashaikh** [Azure/azure-webjobs-sdk-templates#96]
App: functions1f748f5a 

I used http://www.cronmaker.com/ (from google search) to generate a few expressions 
e.g
hourly
0 0 0/1 1/1 * ? *
every minute
0 0/1 * 1/1 * ? *

but we dont seem to support them.
2016-03-29T17:49:28.083 Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.TimerTriggerCSharp1'. mscorlib: String was not recognized as a valid TimeSpan.

We should validate the expressions upfront, a UI to generate working expressions would also be handy .

**Comment by mathewc** [comment]
We use the NCrontabl library for our CRON expressions, so we only support what it supports. https://github.com/atifaziz/NCrontab. No plans to change that.

Also note that the TimerTrigger itself lives in https://github.com/Azure/azure-webjobs-sdk-extensions, and that is where the CRON format is defined.
