### ISSUE TITLE
Add rowKey property to Azure Table Storage input binding

### ISSUE THREAD

**Issue by tdykstra** [Azure/azure-webjobs-sdk-templates#97]
To read a single entity and bind to a POCO type you need to specify rowKey but when you add a table input binding in the portal, rowKey is not offered as a field to enter.

**Comment by paulbatum** [comment]
@tdykstra  I am not sure I follow, why would you hardcode the row key into your binding configuration? The row key would be a value that changes per function execution, it would be determined by some other input (probably the trigger).

**Comment by tdykstra** [comment]
I mean the rowKey is not made available even to put a placeholder in it.

**Comment by paulbatum** [comment]
I don't follow. Can you maybe compare this to other input bindings such as the docdb and easy tables input bindings to put it into context?

**Comment by tdykstra** [comment]
Here's another way to present it.  I use the following function.json to retrieve a single table row where the queue message has the row key.  There is no way to create this function.json using the UI because you aren't given access to the rowKey property.

```JSON
{
  "bindings": [
    {
      "queueName": "myqueue-items",
      "connection": "",
      "name": "myQueueItem",
      "type": "queueTrigger",
      "direction": "in"
    },
    {
      "name": "personInTable",
      "type": "table",
      "tableName": "Person",
      "partitionKey": "Test",
      "rowKey": "{queueTrigger}",
      "take": 1,
      "filter": "",
      "connection": "",
      "direction": "in"
    }
  ],
  "disabled": false
}

**Comment by paulbatum** [comment]
Sorry for being slow, makes sense now.

Specifically, the problem is that bindings.json does not specify a UI element for the rowkey.

**Comment by soninaren** [comment]
Will add the row key again after the issue below is resolved.
https://github.com/Azure/azure-webjobs-sdk-script/issues/261

**Comment by fabiocav** [comment]
Just an update; this should now be resolved for C#. If you're working on the automated tests, you should be able to validate that.
