### ISSUE TITLE
ServiceBusQueue binding connection string error

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-webjobs-sdk-templates#99]
Creating a function using the ServiceBusQueue trigger currently triggers the following error on function creation:
```
Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.servicebusssignoffnode'. Microsoft.Azure.WebJobs.ServiceBus: Microsoft Azure WebJobs SDK ServiceBus connection string 'AzureWebJobs' is missing or empty.
2016-03-29T20:55:45  Welcome, you are now connected to log-streaming service.

```

**Comment by mathewc** [comment]
Yeah, when we did the multi-storage account support for Queues/Blobs/Tables we left it as a TODO to do for the ServiceBus binding. So currently you need to have the **AzureWebJobsServiceBus** app setting containing your SB connection string.

**Comment by fabiocav** [comment]
Makes sense. I'm updating the title as it impacts other languages as well.

**Comment by paulbatum** [comment]
David and I have made the call to yank service bus from beta. This applies for the template, the trigger binding (they might need to be deleted tempoarily because i dont think we have a way to hide them right now), and we'll take the script PR post beta.
